const state = { currentView: 'overview', overview: null, shap: null, evt: null, graph: null, accidents: [], riskResult: null };
const titles = {
  overview: ['风险驾驶舱', '一屏掌握道路风险脉搏'],
  accidents: ['事故数据分析', '从历史事故中解释风险因素'],
  evt: ['轨迹极值分析', '用极端冲突指标识别风险底线'],
  graph: ['风险知识图谱', '把因素、阈值、案例和措施连成证据链'],
  agent: ['智能研判与处置', '让风险结论进入可执行的事件流程'],
};

const $ = (selector) => document.querySelector(selector);
const app = $('#app');

async function api(path, options = {}) {
  const res = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options });
  if (!res.ok) throw new Error((await res.text()) || `请求失败 ${res.status}`);
  return res.json();
}
function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch])); }
function riskBadge(level) { const cls = level === '高' || level === '极高' ? 'risk-high' : level === '中' ? 'risk-mid' : level === '低' ? 'risk-low' : 'risk-unknown'; return `<span class="risk-badge ${cls}">${esc(level || '未知')}</span>`; }
function tag(text, cls='') { return text ? `<span class="tag ${cls}">${esc(text)}</span>` : ''; }
function showToast(text) { const el = $('#toast'); el.textContent = text; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); }
function fmtList(text, sep=';') { return String(text || '').split(sep).filter(Boolean).slice(0, 4).map(x => tag(x.trim())).join('') || '<span class="muted">暂无</span>'; }
function panel(title, subtitle, body, action='') { return `<section class="panel"><div class="panel-header"><div><div class="panel-title">${title}</div>${subtitle ? `<div class="panel-subtitle">${subtitle}</div>` : ''}</div>${action ? `<button class="panel-action" data-action="${action}">查看全部</button>` : ''}</div>${body}</section>`; }
function maxValue(items) { return Math.max(1, ...items.map(x => Number(x.value) || 0)); }
function barChart(items, color='') { const max = maxValue(items); return `<div class="bar-chart">${items.map(x => `<div class="bar-row"><div class="bar-label" title="${esc(x.name)}">${esc(x.name)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4, (Number(x.value) / max) * 100)}%;${color ? `background:${color}` : ''}"></div></div><div class="bar-value">${esc(x.value)}</div></div>`).join('')}</div>`; }
function sparkline(items) { const max = maxValue(items); return `<div class="sparkline">${items.map(x => `<div class="spark-col"><div class="spark-bar" style="height:${Math.max(8,(Number(x.value)/max)*76)}px"></div><div class="spark-label">${esc((x.name || '').slice(5))}</div></div>`).join('')}</div>`; }
function levelDonut(items) { const colors = ['#ee6e83','#f3af53','#4a6cff','#6cc8b8']; let cursor=0; const total=items.reduce((a,x)=>a+Number(x.value),0)||1; const stops=[]; items.forEach((x,i)=>{ const next=cursor+Number(x.value)/total*360; stops.push(`${colors[i%colors.length]} ${cursor}deg ${next}deg`); cursor=next; }); return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops.join(',')})"></div><div class="legend">${items.map((x,i)=>`<div class="legend-row"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span>${esc(x.name)} <strong>${esc(x.value)}</strong></div>`).join('')}</div></div>`; }

async function loadOverview() { state.overview = await api('/api/overview'); }
async function loadAnalysis() { [state.shap, state.evt] = await Promise.all([api('/api/shap/summary'), api('/api/evt/summary')]); }
async function loadGraph() { state.graph = await api('/api/knowledge/graph'); }

function renderOverview() {
  const o = state.overview; const d = o.dataset;
  const risk = o.risk_distribution || []; const events = o.event_distribution || [];
  const stats = [
    ['论文事故案例', d.accident_cases, '105 条人工核验标签数据', '数据快照'],
    ['风险知识条目', d.shap_factors + d.evt_rules, 'SHAP + EVT 规则', '已载入'],
    ['高风险案例', (risk.find(x => x.name === '高') || {value:0}).value, '基于论文风险标签', '需关注'],
    ['可用相似案例', d.accident_cases, '支持案例检索与复盘', '知识库'],
  ];
  const recent = (o.recent_cases || []).map(row => `<tr><td><button class="case-link" data-case="${esc(row.case_id)}">${esc(row.case_id)}</button></td><td>${esc(row.date)}<br><span class="muted">${esc(row.time_period)}</span></td><td>${esc(row.event_type)}</td><td>${esc(row.road_geometry)} · ${esc(row.mileage)}</td><td>${riskBadge(row.risk_level)}</td><td>${fmtList(row.disposal_tags)}</td></tr>`).join('');
  app.innerHTML = `<div class="view">
    <div class="hero-card"><div><div class="hero-title">论文研究成果已接入演示平台</div><div class="hero-copy">当前系统以论文中的 105 条事故案例、33 条风险预测明细、SHAP 先验因素和 TDTC/MTTC 阈值规则作为基础数据，展示从风险解释到事故处置的完整链路。</div></div><div class="hero-badge">● Demo · 可追溯证据模式</div></div>
    <div class="grid stats-grid">${stats.map(s => `<div class="stat-card"><div class="stat-label">${s[0]}</div><div class="stat-value">${esc(s[1])}</div><div class="stat-meta"><b>${s[3]}</b> · ${s[2]}</div></div>`).join('')}</div>
    <div class="grid two-col"><div>${panel('风险等级分布','论文 105 条事故案例的风险标签',levelDonut(risk))}</div><div>${panel('事故类型分布','案例标准标签中的主要事件类型',barChart(events.slice(0,6)))}</div></div>
    <div class="grid two-col" style="margin-top:18px"><div>${panel('案例月度趋势','按事故发生日期统计',sparkline(o.monthly_trend || []))}</div><div>${panel('路段案例覆盖','论文数据覆盖的道路和案例量',barChart(o.top_roads || []))}</div></div>
    <div style="margin-top:18px">${panel('最近案例','可点击进入案例详情与智能研判',`<div class="table-wrap"><table class="data-table"><thead><tr><th>案例编号</th><th>发生时间</th><th>事件类型</th><th>道路位置</th><th>风险</th><th>处置标签</th></tr></thead><tbody>${recent || '<tr><td colspan="6" class="empty">暂无数据</td></tr>'}</tbody></table></div>`)}</div>
  </div>`;
}

function renderAccidents() {
  const items = state.accidents;
  const rows = items.map(row => `<tr><td><button class="case-link" data-case="${esc(row.case_id)}">${esc(row.case_id)}</button></td><td>${esc(row.date)}<br><span class="muted">${esc(row.time)}</span></td><td>${esc(row.event_type)}<br>${fmtList(row.participant_types, ';')}</td><td>${esc(row.road_name)}<br><span class="muted">${esc(row.road_geometry)} · ${esc(row.mileage)}</span></td><td>${esc(row.weather)} · ${esc(row.day_night)}</td><td>${riskBadge(row.risk_level)}</td><td>${fmtList(row.cause_tags, ';')}</td></tr>`).join('');
  const shapItems = (state.shap?.items || []).slice(0,6);
  app.innerHTML = `<div class="view">
    <div class="grid two-col"><div>${panel('SHAP 风险因素排名','论文风险知识中的特征影响示例',`<div class="feature-list">${shapItems.map(x=>`<div class="feature-row"><div><div class="feature-name">${esc(x.feature)}</div><div class="feature-source">${esc(x.source)}</div></div><div class="feature-score">${Number(x.value).toFixed(3)}</div></div>`).join('')}</div><div class="disclaimer" style="margin-top:14px">${esc(state.shap?.disclaimer || '')}</div>`)}</div><div>${panel('事故分析任务','当前使用论文案例标签快照',`<div class="kpi-line"><span class="kpi-label">可分析案例</span><span class="kpi-value">105</span></div><div class="kpi-line"><span class="kpi-label">数据来源</span><span class="kpi-value">人工核验阶段1</span></div><div class="kpi-line"><span class="kpi-label">解释类型</span><span class="kpi-value">全局 + 局部</span></div><div class="kpi-line"><span class="kpi-label">结果状态</span><span class="kpi-value">示例已发布</span></div><button class="primary-btn" data-action="toast" style="margin-top:16px">创建分析任务</button>`)}</div></div>
    <div class="panel" style="margin-top:18px"><div class="panel-header"><div><div class="panel-title">事故案例数据</div><div class="panel-subtitle">支持搜索、风险筛选和进入单案例解释</div></div><div class="button-row" style="margin:0"><input id="accidentSearch" class="field-input" placeholder="搜索案例、事件类型或道路" style="border:1px solid #e1e5ef;border-radius:8px;padding:8px 10px;width:220px"><select id="riskFilter" style="border:1px solid #e1e5ef;border-radius:8px;padding:8px 10px;color:#5c6881"><option value="">全部风险</option><option>低</option><option>中</option><option>高</option></select><button class="secondary-btn" id="searchAccidents">筛选</button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>案例编号</th><th>时间</th><th>事件与参与者</th><th>道路位置</th><th>环境</th><th>风险标签</th><th>原因标签</th></tr></thead><tbody>${rows || '<tr><td colspan="7" class="empty">暂无数据</td></tr>'}</tbody></table></div></div>
  </div>`;
  $('#searchAccidents')?.addEventListener('click', async()=>{ const q=$('#accidentSearch').value; const level=$('#riskFilter').value; const res=await api(`/api/accidents?limit=105&search=${encodeURIComponent(q)}&risk_level=${encodeURIComponent(level)}`); state.accidents=res.items; renderAccidents(); });
}

function renderEvt() {
  const items = state.evt?.items || []; const rows=items.map(x=>`<tr><td><strong>${esc(x.indicator)}</strong></td><td>${x.threshold == null ? '<span class="muted">待标定</span>' : `<strong>${esc(x.threshold)}</strong> ${esc(x.unit)}`}</td><td>${riskBadge(x.risk_level)}</td><td>${esc(x.rule)}</td><td>${tag(x.status, x.status==='待发布'?'orange':'green')}</td></tr>`).join('');
  app.innerHTML=`<div class="view"><div class="hero-card"><div><div class="hero-title">冲突指标 → 极值阈值 → 风险底线</div><div class="hero-copy">轨迹模块当前以论文中的 TDTC、MTTC、PET、ΔV 指标体系为产品入口。TDTC 和 MTTC 展示论文中用于规则判定的示例阈值，正式部署时应绑定路段、样本范围与模型版本。</div></div><div class="hero-badge">POT / GPD / GEV</div></div><div class="grid three-col">${[['TDTC','1.5 s','高风险底线'],['MTTC','2.0 s','高风险关注'],['待标定指标','PET / ΔV','需要轨迹样本']].map(x=>`<div class="mini-card"><div class="mini-card-title">${x[0]}</div><div class="mini-card-value">${x[1]}</div><div class="stat-meta">${x[2]}</div></div>`).join('')}</div><div class="grid two-col" style="margin-top:18px"><div>${panel('极值规则清单','论文示例规则与待发布指标',`<div class="table-wrap"><table class="data-table"><thead><tr><th>指标</th><th>阈值</th><th>等级</th><th>判定说明</th><th>状态</th></tr></thead><tbody>${rows}</tbody></table></div>`)}</div><div>${panel('模型运行状态','演示环境任务状态',`<div class="kpi-line"><span class="kpi-label">轨迹数据接入</span><span class="kpi-value">待接入</span></div><div class="kpi-line"><span class="kpi-label">冲突指标计算</span><span class="kpi-value">接口已预留</span></div><div class="kpi-line"><span class="kpi-label">极值拟合</span><span class="kpi-value">规则快照可用</span></div><div class="kpi-line"><span class="kpi-label">告警触发</span><span class="kpi-value">支持 TDTC / MTTC</span></div><button class="primary-btn" data-action="toast" style="margin-top:16px">上传轨迹数据</button>`)}</div></div><div class="panel" style="margin-top:18px">${panel('使用说明','产品约束',`<div class="disclaimer">触发阈值后，风险 Agent 的输出等级不得低于规则判定等级。当前页面不把阈值示例误认为跨路段通用结论；正式发布必须经过样本量、拟合稳定性、置信区间和专家审核。</div>`)}</div></div>`;
}

function graphSvg(graph) {
  const pos={n1:[90,75],n2:[90,170],n3:[90,265],n4:[280,55],n5:[280,155],n6:[280,255],n7:[485,155],n8:[650,85],n9:[650,235]};
  const colors={factor:'#5d7bff',scene:'#9c73e8',indicator:'#f3aa4d',risk:'#eb6a82',case:'#4dbba7',measure:'#7482a8'};
  const lines=graph.edges.map(e=>{const [x1,y1]=pos[e.source], [x2,y2]=pos[e.target]; return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="graph-edge"/><text x="${(x1+x2)/2}" y="${(y1+y2)/2-5}" class="graph-edge-label">${esc(e.label)}</text>`}).join('');
  const nodes=graph.nodes.map(n=>{const [x,y]=pos[n.id]||[100,100]; return `<g class="graph-node"><circle cx="${x}" cy="${y}" r="18" fill="${colors[n.group]||'#7482a8'}"/><text x="${x}" y="${y+36}" text-anchor="middle">${esc(n.label)}</text></g>`}).join('');
  return `<svg viewBox="0 0 760 330" role="img" aria-label="风险知识图谱">${lines}${nodes}</svg>`;
}
function renderGraph() {
  const g=state.graph; const nodeCount=g?.nodes?.length||0; const edgeCount=g?.edges?.length||0;
  app.innerHTML=`<div class="view"><div class="hero-card"><div><div class="hero-title">风险因素、冲突阈值和处置措施的证据链</div><div class="hero-copy">图谱模块承担索引和推理作用，案例知识库承担叙事内容。每条边都带有来源类型，支持从“为什么危险”跳转到“过去如何处置”。</div></div><div class="hero-badge">${nodeCount} 个节点 · ${edgeCount} 条关系</div></div><div class="grid two-col"><div>${panel('风险知识图谱子图','论文知识本体的可视化种子数据',`<div class="graph-stage">${graphSvg(g)}</div><div class="graph-legend"><span><i class="legend-square" style="background:#5d7bff"></i>风险因素</span><span><i class="legend-square" style="background:#f3aa4d"></i>冲突指标</span><span><i class="legend-square" style="background:#eb6a82"></i>风险等级</span><span><i class="legend-square" style="background:#4dbba7"></i>历史案例</span></div>`)}</div><div>${panel('知识检索示例','输入场景即可查看相似案例和证据',`<div class="field"><label>场景关键词</label><input id="graphQuery" placeholder="例如：夜间 匝道 货车 追尾" value="夜间 匝道 货车"></div><div class="button-row"><button class="primary-btn" id="graphSearch">检索案例</button><button class="secondary-btn" data-action="toast">打开知识管理</button></div><div id="graphResults" class="result-section"><div class="disclaimer">检索结果将按论文案例标签进行显式匹配，并保留案例编号、道路位置和处置标签。</div></div>`)}</div></div></div>`;
  $('#graphSearch')?.addEventListener('click', async()=>{ const q=$('#graphQuery').value; const res=await api(`/api/cases/search?q=${encodeURIComponent(q)}`); $('#graphResults').innerHTML=`<div class="result-title">匹配案例 ${res.items.length} 条</div>${res.items.map(x=>`<div class="evidence-item"><strong>${esc(x.case_id)}</strong> · ${esc(x.event_type)}<br><span class="muted">${esc(x.road)} ${esc(x.location)} · ${esc(x.weather)} · ${esc(x.scene)}</span><div style="margin-top:6px">${fmtList(x.disposal_tags)}</div></div>`).join('')||'<div class="empty">没有找到匹配案例</div>'}`; });
}

function renderAgent() {
  const r=state.riskResult;
  const resultHtml=r?`<div class="risk-result"><div class="risk-header"><div><div class="result-title">综合风险等级</div><div class="risk-level">${riskBadge(r.risk_level)} <span style="font-size:14px;color:#69748e;margin-left:8px">置信度 ${esc(r.confidence)}</span></div></div><div class="risk-index">风险指数 <strong>${esc(r.risk_index)}</strong></div></div><div class="result-section"><div class="result-title">风险摘要</div><div class="evidence-item">${esc(r.summary)}</div></div><div class="result-section"><div class="result-title">关键因素</div><div>${(r.risk_causes||[]).map(x=>tag(x,'blue')).join('')}</div></div><div class="result-section"><div class="result-title">阈值判定</div>${(r.threshold_results||[]).map(x=>`<div class="evidence-item"><strong>${esc(x.indicator)}</strong>：${esc(x.value)} ${x.threshold && x.threshold!=='-' ? `，阈值 ${esc(x.threshold)}`:''} · ${riskBadge(x.level||'未触发')}</div>`).join('')}</div><div class="result-section"><div class="result-title">证据链</div>${(r.evidence||[]).slice(0,7).map(x=>`<div class="evidence-item"><span class="tag blue">${esc(x.type)}</span> ${esc(x.statement)}<div class="muted" style="margin-top:5px">来源：${esc(x.source)}</div></div>`).join('')}</div><div class="result-section"><div class="result-title">建议处置方案</div>${(r.recommendations||[]).map(x=>`<div class="recommendation-item"><div class="priority">${esc(x.priority)}</div><div><div class="recommendation-title">${esc(x.title)}</div><div class="recommendation-copy">${esc(x.action)}</div><div class="muted" style="margin-top:5px">依据：${esc(x.source)}</div></div></div>`).join('')}</div><div class="result-section"><div class="result-title">待核验事项</div><div class="disclaimer">${(r.unknown_or_to_verify||[]).map(esc).join('；')}</div></div><div class="button-row"><button class="primary-btn" data-action="toast">保存报告草案</button><button class="secondary-btn" data-action="toast">导出审核版</button></div><div class="muted" style="margin-top:12px">${esc(r.generated_by)}</div></div>`:'<div class="empty">填写左侧事件信息后，生成结构化风险研判和处置建议。</div>';
  app.innerHTML=`<div class="view"><div class="grid two-col"><div>${panel('新建风险事件','支持人工描述、指标输入和场景补充',`<div class="form-grid"><div class="field full"><label>事件描述</label><textarea id="riskDescription" placeholder="例如：夜间暴雨，东南西环高速长下坡路段，两辆货车发生追尾，TDTC 约 1.2 秒">${esc(r?.input?.description||'')}</textarea></div><div class="field"><label>道路场景</label><select id="roadScene"><option>高速公路主线</option><option>匝道</option><option>长下坡</option><option>施工/作业区</option></select></div><div class="field"><label>天气</label><select id="weather"><option>晴</option><option>暴雨</option><option>大雨</option><option>雾</option></select></div><div class="field"><label>时段</label><select id="timePeriod"><option>日间</option><option>早高峰</option><option>晚高峰</option><option>夜间</option><option>深夜</option></select></div><div class="field"><label>车辆类型</label><select id="vehicleType"><option>小客车</option><option>货车</option><option>客车</option><option>拖挂车</option></select></div><div class="field"><label>TDTC（秒，可选）</label><input id="tdtc" type="number" step="0.1" placeholder="例如 1.2"></div><div class="field"><label>MTTC（秒，可选）</label><input id="mttc" type="number" step="0.1" placeholder="例如 1.8"></div></div><div class="button-row"><button class="primary-btn" id="runRisk">生成风险研判</button><button class="secondary-btn" id="fillSample">填充论文示例</button></div><div class="disclaimer" style="margin-top:16px">当前为论文数据演示适配器：规则、图谱和案例来自论文快照；未接入外部大语言模型时，系统使用模板化知识增强推理，后续可替换为本地或远程 LLM。</div>`)}</div><div>${panel('风险研判结果','规则底线 + 图谱证据 + 相似案例 + 处置建议',resultHtml)}</div></div></div>`;
  $('#fillSample')?.addEventListener('click',()=>{ $('#riskDescription').value='夜间暴雨，东南西环高速长下坡路段，两辆货车发生追尾，TDTC 约 1.2 秒'; $('#roadScene').value='长下坡'; $('#weather').value='暴雨'; $('#timePeriod').value='深夜'; $('#vehicleType').value='货车'; $('#tdtc').value='1.2'; $('#mttc').value='1.8'; });
  $('#runRisk')?.addEventListener('click', runRisk);
}
async function runRisk(){ const payload={description:$('#riskDescription').value,road_scene:$('#roadScene').value,weather:$('#weather').value,time_period:$('#timePeriod').value,vehicle_type:$('#vehicleType').value,event_type:'追尾/碰撞',tdtc:$('#tdtc').value?Number($('#tdtc').value):null,mttc:$('#mttc').value?Number($('#mttc').value):null}; try{ const result=await api('/api/risk/analyze',{method:'POST',body:JSON.stringify(payload)}); result.input=payload; state.riskResult=result; renderAgent(); showToast('风险研判已生成'); }catch(e){ showToast(e.message); } }

async function showCase(caseId){ try{ const row=await api(`/api/accidents/${encodeURIComponent(caseId)}`); const pred=row.risk_prediction||{}; state.riskResult=null; app.innerHTML=`<div class="view"><button class="panel-action" data-back>← 返回事故分析</button><div class="hero-card" style="margin-top:12px"><div><div class="hero-title">${esc(row.case_id)} · ${esc(row.event_type)}</div><div class="hero-copy">${esc(row.date)} ${esc(row.time)} · ${esc(row.road_name)} ${esc(row.mileage)} · ${esc(row.road_geometry)} · ${esc(row.weather)} · ${esc(row.day_night)}</div></div><div>${riskBadge(row.risk_level)}</div></div><div class="grid two-col"><div>${panel('案例基本信息','论文人工核验标签',`<div class="kpi-line"><span class="kpi-label">参与者</span><span class="kpi-value">${esc(row.participant_types)} · ${esc(row.vehicle_count)} 辆</span></div><div class="kpi-line"><span class="kpi-label">伤亡</span><span class="kpi-value">${esc(row.casualty)}</span></div><div class="kpi-line"><span class="kpi-label">路产损失</span><span class="kpi-value">${esc(row.road_property_loss)}</span></div><div class="kpi-line"><span class="kpi-label">原因标签</span><span class="kpi-value">${esc(row.cause_tags)}</span></div><div class="kpi-line"><span class="kpi-label">处置标签</span><span class="kpi-value">${esc(row.disposal_tags)}</span></div>`)}</div><div>${panel('知识增强预测','论文实验结果明细',`<div class="kpi-line"><span class="kpi-label">规则基线</span><span class="kpi-value">${esc(pred.gold_level||'暂无')}</span></div><div class="kpi-line"><span class="kpi-label">知识图谱等级</span><span class="kpi-value">${esc(pred.kg_level||'暂无')}</span></div><div class="kpi-line"><span class="kpi-label">融合等级</span><span class="kpi-value">${esc(pred.fusion_level||'暂无')}</span></div><div class="kpi-line"><span class="kpi-label">LLM + 图谱/Wiki</span><span class="kpi-value">${esc(pred.llm_level||'暂无')}</span></div><div class="kpi-line"><span class="kpi-label">图谱证据数</span><span class="kpi-value">${esc(pred.graph_evidence_count||'0')}</span></div>`)}</div></div><div class="grid two-col" style="margin-top:18px"><div>${panel('图谱证据预览','来自论文风险推理实验',`<div class="disclaimer">${esc(pred.graph_evidence_preview||'该案例暂无实验明细')}</div>`)}</div><div>${panel('相似案例预览','用于事故处置参考',`<div class="disclaimer">${esc(pred.similar_case_preview||'暂无相似案例摘要')}</div>`)}</div></div></div>`; $('#app [data-back]')?.addEventListener('click',()=>{state.currentView='accidents';render();}); }catch(e){showToast(e.message)} }

async function render(){ $('#pageTitle').textContent=titles[state.currentView][0]; $('#pageHeading').textContent=titles[state.currentView][1]; document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.currentView)); if(state.currentView==='overview'){if(!state.overview)await loadOverview();renderOverview()} else if(state.currentView==='accidents'){if(!state.shap)await loadAnalysis();if(!state.accidents.length){const res=await api('/api/accidents?limit=105');state.accidents=res.items}renderAccidents()} else if(state.currentView==='evt'){if(!state.evt)await loadAnalysis();renderEvt()} else if(state.currentView==='graph'){if(!state.graph)await loadGraph();renderGraph()} else if(state.currentView==='agent'){renderAgent()} }

document.addEventListener('click', (e)=>{ const nav=e.target.closest('.nav-item'); if(nav){state.currentView=nav.dataset.view;render();return} const caseBtn=e.target.closest('[data-case]'); if(caseBtn){showCase(caseBtn.dataset.case);return} const action=e.target.closest('[data-action]'); if(action&&action.dataset.action==='toast')showToast('演示功能已预留：后续可接入任务队列或报告服务'); });
render().catch(e=>{app.innerHTML=`<div class="panel"><div class="empty">系统加载失败：${esc(e.message)}</div></div>`});
